version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - gosec
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G104
      - G101
  misspell:
    locale: US

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/Laminar-Bot/helius-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
